### ISSUE TITLE
Missing token / Security header is not valid

### ISSUE THREAD

**Issue by fiatjaf** [uncedric/paypal-recurring2#2]
When making the call to `paypal.authenticate` I get this response:

``` javascript
{ TIMESTAMP: '2015-06-24T16:41:57Z',
  CORRELATIONID: '3638a82437065',
  ACK: 'Failure',
  VERSION: '94',
  BUILD: '17159089',
  L_ERRORCODE0: '10002',
  L_SHORTMESSAGE0: 'Security error',
  L_LONGMESSAGE0: 'Security header is not valid',
  L_SEVERITYCODE0: 'Error' }
```

Which is translated into a "Missing token" error.

Why is my security header not valid? How can I fix it?

**Comment by fiatjaf** [comment]
It works if I go to "production", using the same credentials. I probably need some sandbox credentials. I only need to discover where I'll get them.

**Comment by fiatjaf** [comment]
API credentials for test accounts: https://developer.paypal.com/developer/accounts

**Comment by uncedric** [comment]
Yup, that was the problem :) glad you could fix it, your last comment could be integrated in the README.md file instead of the former pull request you sent :smile:

**Comment by fiatjaf** [comment]
Now my code works in test mode, but has suddenly stopped working (failing with "Missing token") in production. I've checked the place where I got my previous production API name, password and signature and they haven't changed. Bizarre thing: I've even collected payments using my current setup, then I haven't changed it, but now it doesn't work anymore. (Ok, in fact I've changed the description of the subscription request, but it will be madness if that is the cause).

Do you have a clue on why could this be happening?

**Comment by fiatjaf** [comment]
Now I've tested with my previous description and return URLs, but it has failed again.

**Comment by fiatjaf** [comment]
Ok, the problem is this: https://github.com/uncedric/paypal-recurring2/commit/ef89959be161289899bc7db169f8cba2b1f8b22a#diff-4417fdadcb17112bdcb41567a59c8becL31
